function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export default async function handler(req, res) {
  const image = req.query?.image;

  if (!image) {
    return res.status(400).send("Missing image.");
  }

  let imageUrl;
  try {
    imageUrl = decodeURIComponent(image);
    const url = new URL(imageUrl);

    // Only allow Cloudinary delivery URLs generated by our upload flow.
    if (url.protocol !== "https:" || !url.hostname.endsWith(".cloudinary.com")) {
      return res.status(400).send("Invalid image host.");
    }
  } catch {
    return res.status(400).send("Invalid image URL.");
  }

  const safeImage = escapeHtml(imageUrl);
  const title = "HH Goa 2026 Builder Pass";
  const description =
    "HH Goa 2026 Builder Pass — building, connecting and vibing in Goa. #FrameInGoa";

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title>
<meta name="description" content="${description}">
<meta property="og:type" content="website">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:image" content="${safeImage}">
<meta property="og:image:secure_url" content="${safeImage}">
<meta property="og:image:type" content="image/png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${title}">
<meta name="twitter:description" content="${description}">
<meta name="twitter:image" content="${safeImage}">
<style>
body{font-family:system-ui,sans-serif;margin:0;background:#062d27;color:#fff;display:grid;place-items:center;min-height:100vh}
main{text-align:center;max-width:760px;padding:24px}
img{max-width:100%;height:auto;border-radius:18px;box-shadow:0 20px 60px #0008}
p{opacity:.8}
</style>
</head>
<body>
<main>
<h1>HH Goa 2026 Builder Pass</h1>
<img src="${safeImage}" alt="HH Goa 2026 Builder Pass">
<p>Build. Connect. Vibe. 🌴</p>
</main>
</body>
</html>`;

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=300, s-maxage=300");
  return res.status(200).send(html);
}
